export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const R_PASSWORD_CHANGED = "R_PASSWORD_CHANGED";
export const NAME_CHANGED = "NAME_CHANGED";
export const REGISTER_SUCCSESS = "REGISTER_SUCCSESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const SAVE_DATA_TO_DB = "SAVE_DATA_TO_DB";
<<<<<<< HEAD
=======
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";




>>>>>>> 6576c2cca14e41d635fde145d5ad2f9eb375561d




